"""Initial Schema

Revision ID: 374430534504
Revises: 
Create Date: 2025-10-03 23:51:08.786198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374430534504'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mr_number', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mr_number')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_type', sa.String(length=120), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('signer_name', sa.String(length=120), nullable=True),
    sa.Column('signature_date', sa.Date(), nullable=True),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('diet', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bp_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vital_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('systolic', sa.String(length=10), nullable=True),
    sa.Column('diastolic', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['vital_id'], ['vital_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulse_resp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vital_id', sa.Integer(), nullable=True),
    sa.Column('pulse_apical', sa.String(length=20), nullable=True),
    sa.Column('pulse_radial', sa.String(length=20), nullable=True),
    sa.Column('resp_rate', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['vital_id'], ['vital_signs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulse_resp')
    op.drop_table('bp_measurements')
    op.drop_table('vital_signs')
    op.drop_table('signatures')
    op.drop_table('assessments')
    op.drop_table('visits')
    op.drop_table('patients')
    # ### end Alembic commands ###
