"""add Visit Assesment Table

Revision ID: d5c274ea4f60
Revises: dd3d73f77a0b
Create Date: 2025-10-04 18:08:22.195730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c274ea4f60'
down_revision = 'dd3d73f77a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('personal_care', sa.JSON(), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('mental_status', sa.JSON(), nullable=True),
    sa.Column('elimination', sa.JSON(), nullable=True),
    sa.Column('activity', sa.JSON(), nullable=True),
    sa.Column('assistive_device', sa.JSON(), nullable=True),
    sa.Column('house_keeping', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('time_in', sa.String(length=20), nullable=True),
    sa.Column('time_out', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    op.drop_table('visit_assessments')
    # ### end Alembic commands ###
